sudo: required
services: docker

arch:
  packages:
    - gcc
    - cmake
    - make
  script:
    - cmake . && make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"